# Project information
site_name: Citrix NetScaler SDX 12.0 Command Reference
site_description: Citrix NetScaler SDX 12.0 Command Reference
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/devdocs-issue-collector/issues/new
assignees_uri:
  - subbendumajumder
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'

# Page tree
nav:
  - Home: index.md
  - System:
    - System: system/system.md 
    - aaaserver: system/aaaserver.md
    - admindomaininfo: system/admindomaininfo.md
    - appcategory: system/appcategory.md
    - backup: system/backup.md
    - backupexternalstorage: system/backupexternalstorage.md
    - backupfile: system/backupfile.md
    - backuppolicy: system/backuppolicy.md
    - capacity: system/capacity.md
    - centralmanagmentserver: system/centralmanagmentserver.md
    - ciphergroup: system/ciphergroup.md
    - ciphersuite: system/ciphersuite.md
    - cliprompt: system/cliprompt.md
    - configjob: system/configjob.md
    - configjobdetails: system/configjobdetails.md
    - configtemplateexecute: system/configtemplateexecute.md
    - configurationtemplate: system/configurationtemplate.md
    - configvariable: system/configvariable.md
    - device_values_map: system/device_values_map.md
    - devicelicenseinfo: system/devicelicenseinfo.md
    - deviceprofile: system/deviceprofile.md
    - eventrule_variable_values: system/eventrule_variable_values.md
    - hostname: system/hostname.md
    - ip_block: system/ip_block.md
    - ldapserver: system/ldapserver.md
    - license: system/license.md
    - licensefile: system/licensefile.md
    - licenseproxyserver: system/licenseproxyserver.md
    - licenseserver: system/licenseserver.md
    - licenseserverinfo: system/licenseserverinfo.md
    - licenseserverpool: system/licenseserverpool.md
    - mail_attachment: system/mail_attachment.md
    - mailprofile: system/mailprofile.md
    - maintenancejob: system/maintenancejob.md
    - manageddevice: system/manageddevice.md
    - manageddevicesummary: system/manageddevicesummary.md
    - managementservicestatistics: system/managementservicestatistics.md
    - mas_agent_image: system/mas_agent_image.md
    - mgmtsystemutility: system/mgmtsystemutility.md
    - mps_geolocation_region: system/mps_geolocation_region.md
    - networkconfig: system/networkconfig.md
    - networkpool: system/networkpool.md
    - ntpparam: system/ntpparam.md
    - ntpserver: system/ntpserver.md
    - ntpsync: system/ntpsync.md
    - passwordpolicy: system/passwordpolicy.md
    - platform_specs: system/platform_specs.md
    - prunepolicy: system/prunepolicy.md
    - radiusserver: system/radiusserver.md
    - rba_authscope_props: system/rba_authscope_props.md
    - rba_client_data: system/rba_client_data.md
    - rba_module_client_data: system/rba_module_client_data.md
    - rba_operation: system/rba_operation.md
    - rba_operation_client_data: system/rba_operation_client_data.md
    - rba_policy: system/rba_policy.md
    - rba_resourcegroup: system/rba_resourcegroup.md
    - rba_resourcegroup_props: system/rba_resourcegroup_props.md
    - rba_role: system/rba_role.md
    - rba_statement: system/rba_statement.md
    - rba_submodule_client_data: system/rba_submodule_client_data.md
    - rba_ui: system/rba_ui.md
    - rediscover: system/rediscover.md
    - singlebundleimage: system/singlebundleimage.md
    - singlebundleinfo: system/singlebundleinfo.md
    - singlebundleupgrade: system/singlebundleupgrade.md
    - smsprofile: system/smsprofile.md
    - smsserver: system/smsserver.md
    - snmpalarm: system/snmpalarm.md
    - snmpinfo: system/snmpinfo.md
    - snmpmanager: system/snmpmanager.md
    - snmpmib: system/snmpmib.md
    - snmptrap: system/snmptrap.md
    - snmpuser: system/snmpuser.md
    - snmpview: system/snmpview.md
    - sslcertfile: system/sslcertfile.md
    - sslcertificate: system/sslcertificate.md
    - sslciphers: system/sslciphers.md
    - sslkeyfile: system/sslkeyfile.md
    - sslsettings: system/sslsettings.md
    - sslv3setting: system/sslv3setting.md
    - startstat: system/startstat.md
    - syslogparameters: system/syslogparameters.md
    - syslogserver: system/syslogserver.md
    - systembackuprestore: system/systembackuprestore.md
    - systemgroup: system/systemgroup.md
    - systemimage: system/systemimage.md
    - systemsession: system/systemsession.md
    - systemsettings: system/systemsettings.md
    - systemstatus: system/systemstatus.md
    - systemupgrade: system/systemupgrade.md
    - systemuser: system/systemuser.md
    - tacacsserver: system/tacacsserver.md
    - taskdevicelog: system/taskdevicelog.md
    - techsupport: system/techsupport.md
    - tenant: system/tenant.md
    - timezone: system/timezone.md
    - userlockoutpolicy: system/userlockoutpolicy.md
    - variable_values: system/variable_values.md
    - vlandetails: system/vlandetails.md
    - vlansummary: system/vlansummary.md
    - vmdevice: system/vmdevice.md
  - NetScaler: 
    - NetScaler: netscaler/netscaler.md
    - ns: netscaler/ns.md
    - ns_summary: netscaler/ns_summary.md
    - nsdocimage: netscaler/nsdocimage.md
    - nsgslbservice: netscaler/nsgslbservice.md
    - nsimage: netscaler/nsimage.md
    - nspreupgrade: netscaler/nspreupgrade.md
    - nssslcertfile: netscaler/nssslcertfile.md
    - nssslcertkey: netscaler/nssslcertkey.md
    - nssslcertkeypolicy: netscaler/nssslcertkeypolicy.md
    - nssslkeyfile: netscaler/nssslkeyfile.md
    - nsupgrade: netscaler/nsupgrade.md
    - nsvmacs: netscaler/nsvmacs.md
    - visualizercsvserver: netscaler/visualizercsvserver.md
    - visualizergslbdomain: netscaler/visualizergslbdomain.md
    - visualizerlbvserver: netscaler/visualizerlbvserver.md
  - XenServer:
    - XenServer: xenserver/xenserver.md
    - appliance: xenserver/appliance.md
    - channel: xenserver/channel.md
    - channelinfo: xenserver/channelinfo.md
    - cleaninstall: xenserver/cleaninstall.md
    - cpucoreusage: xenserver/cpucoreusage.md
    - fipspartition: xenserver/fipspartition.md
    - hostinterface: xenserver/hostinterface.md
    - raidlogicaldrive: xenserver/raidlogicaldrive.md
    - raidphysicaldrive: xenserver/raidphysicaldrive.md
    - systemhealth: xenserver/systemhealth.md
    - systemhealthdisk: xenserver/systemhealthdisk.md
    - systemhealthfanspeed: xenserver/systemhealthfanspeed.md
    - systemhealthhardware: xenserver/systemhealthhardware.md
    - systemhealthpowersupply: xenserver/systemhealthpowersupply.md
    - systemhealthsoftware: xenserver/systemhealthsoftware.md
    - systemhealthstoragerepository: xenserver/systemhealthstoragerepository.md
    - systemhealthtemperature: xenserver/systemhealthtemperature.md
    - systemhealthvoltage: xenserver/systemhealthvoltage.md
    - xen_applied_hotfix: xenserver/xen_applied_hotfix.md
    - xen_health_hsm: xenserver/xen_health_hsm.md
    - xen_hsm: xenserver/xen_hsm.md
    - xenhotfix: xenserver/xenhotfix.md
    - xenhsmfwimage: xenserver/xenhsmfwimage.md
    - xennsvpximage: xenserver/xennsvpximage.md
    - xensupplementalpack: xenserver/xensupplementalpack.md
    - xenupgrade: xenserver/xenupgrade.md
  - Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/